### ISSUE TITLE
PlotlyBase.PlotConfig(scrollZoom=true) does not work as expected

### ISSUE THREAD

**Issue by garibarba** [GenieFramework/StipplePlotly.jl#43]
Description: The scrolling action should result in zooming into the plot but it scrolls the page instead, independently of the pointer location.

Small example to reproduce the issue:
```julia
using Stipple, StipplePlotly
using PlotlyBase

@reactive! mutable struct Example <: ReactiveModel
    plot::R{Plot} = Plot(config = PlotlyBase.PlotConfig(scrollZoom=true, displaylogo=false))
end

function ui(model::Example)
    page(model, class = "container", [
        plot("plot.data", layout = "plot.layout", config = "plot.config")
    ])
end

model = init(Example, debounce=0)
route("/") do
    model |> ui |> html
end

up(8800)
```

Minimal example to see what would be expected:

```julia
using PlotlyBase
Plot(config = PlotlyBase.PlotConfig(scrollZoom=true, displaylogo=false))
```

 Note: `displaylogo` is just there to show that the `config` is working correctly.

**Comment by hhaensel** [comment]
There is `plotly(:plot)` which will probably do what you want.
Have a look at its output
```julia
julia> plotly(:plot)
"<plotly :data=\"plot.data\" :layout=\"plot.layout\" :scrollZoom=\"plot.config.scrollZoom || ''\" :editable=\"plot.config.editable || ''\" :staticPlot=\"plot.config.staticPlot || ''\" :toImageButtonOptions=\"plot.config.toImageButtonOptions || ''\" :displayModeBar=\"plot.config.displayModeBar || ''\" :modeBarButtonsToRemove=\"plot.config.modeBarButtonsToRemove || ''\" :modeBarButtonsToAdd=\"plot.config.modeBarButtonsToAdd || ''\" :modeBarButtons=\"plot.config.modeBarButtons || ''\" :showLink=\"plot.config.showLink || ''\" :plotlyServerURL=\"plot.config.plotlyServerURL || ''\" :linkText=\"plot.config.linkText || ''\" :showEditInChartStudio=\"plot.config.showEditInChartStudio || ''\" :locale=\"plot.config.locale || ''\" :displaylogo=\"plot.config.displaylogo || ''\" :responsive=\"plot.config.responsive || ''\" :doubleClickDelay=\"plot.config.doubleClickDelay || ''\"></plotly>"
```
The reason is that `plot()` by default takes the fields of the StipplePlotly.PlotConfig, while configtype of `plotly()` defaults to PlotlyBase.PlotConfig as soon as PlotlyBase is loaded. Before loading of PlotlyBase it generates fields for a StipplePlotly.PlotConfig.

That having said, I found that rendering StipplePlotly.PlotConfig is more difficult than I initially thought (camelcasing plus serialisation of `toImageButtonOptions`).

I pushed some changes to the main branch, that solve the issue.
@garibarba would you be so kind to test it?

**Comment by garibarba** [comment]
Hey @hhaensel thanks!

I've tried this (note: `watchplots()` without arguments was critical to avoid errors):
```julia
using Stipple, StipplePlotly
using PlotlyBase

@reactive! mutable struct Example <: ReactiveModel
    plot::R{Plot} = Plot(config = PlotlyBase.PlotConfig(scrollZoom=true, displaylogo=false))
    plot_selected::R{Dict{String, Any}} = Dict{String, Any}()
    plot_hover::R{Dict{String, Any}} = Dict{String, Any}()
end

Stipple.js_mounted(::Example) = watchplots()

function ui(model::Example)
    page(model, class = "container", [
        plotly(:plot, syncevents = true)
    ])
end

model = init(Example, debounce=0)
route("/") do
    model |> handlers |> ui |> html
end
function handlers(model)
    on(model.isready) do isready
        isready || return
        push!(model)
    end

    on(model.plot_selected) do data
        haskey(data, "points") && @info "Selection: $(getindex.(data["points"], "pointIndex"))"
    end

    return model
end

up(8800)

model.plot[] = Plot(scatter(y = rand(5)), config = PlotlyBase.PlotConfig(scrollZoom=true, displaylogo=false))
```

Works as expected when selecting points, but the zoom when scrolling is still not working 🤔

**Comment by hhaensel** [comment]
I think I fixed this. Could you please try the latest main branch?
```julia
]add StipplePlotly#main
```

**Comment by garibarba** [comment]
It does work indeed. Thanks for the great work!
